    print('hello, and welcome to the Animal Husbandry Game.')
    print('This game was originally made by Karol Borsuk.')
    print('There are several articles about this game.')
    print('My personal thought:')
    print('\tThis is an important reminder about why we program.')
